'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { BarChart3, Map, Activity, AlertTriangle, Workflow, MapPin } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, Legend, FunnelChart, Funnel, LabelList } from 'recharts';
import { useAuth } from '@/lib/auth';
import AppShell from '@/components/AppShell';
import { getDistrictOperations } from '@/lib/operations';
import { KpiGrid, SectionHeader, StatusPill } from '@/components/OperationalPrimitives';

const TOOLTIP_STYLE = { contentStyle: { background: 'rgba(15,23,42,0.96)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: 8, color: '#e2e8f0', fontSize: 12 }, labelStyle: { color: '#94a3b8' } };

export default function AnalyticsPage() {
  const { isAuthenticated } = useAuth();
  const router = useRouter();
  useEffect(() => { if (!isAuthenticated) router.push('/login'); }, [isAuthenticated, router]);
  const operations = getDistrictOperations();

  return <AppShell><div className="p-5 lg:p-6 max-w-7xl mx-auto">
    <div className="flex items-start justify-between gap-4 mb-5"><div><div className="text-[10px] text-cyan-400 uppercase tracking-widest font-medium mb-1">Executive Operations</div><h1 className="font-heading font-bold text-2xl text-white flex items-center gap-2"><BarChart3 size={20} className="text-cyan-400" /> District Administrator Dashboard</h1><p className="text-sm text-slate-500 mt-1">Raipur district command view: conflicts, workload, services and resolution performance.</p></div><Link href="/map" className="flex items-center gap-1.5 text-xs text-cyan-400 border border-cyan-500/20 rounded-lg px-3 py-2"><Map size={13} /> District GIS</Link></div>
    <KpiGrid metrics={operations.metrics} columns={7} />

    <div className="grid xl:grid-cols-[1.2fr_0.8fr] gap-4 mt-5"><div className="surface-card p-4"><SectionHeader title="District trend" subtitle="Monthly mutation throughput, detected conflicts and resolved workflows" /><ResponsiveContainer width="100%" height={245}><LineChart data={operations.trend}><CartesianGrid strokeDasharray="3 3" stroke="rgba(99,102,241,0.1)" /><XAxis dataKey="month" tick={{ fill: '#64748b', fontSize: 11 }} /><YAxis tick={{ fill: '#64748b', fontSize: 11 }} /><Tooltip {...TOOLTIP_STYLE} /><Legend wrapperStyle={{ fontSize: 10, color: '#94a3b8' }} /><Line type="monotone" dataKey="mutations" stroke="#6366f1" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="conflicts" stroke="#ef4444" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="resolved" stroke="#10b981" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div><div className="surface-card p-4"><SectionHeader title="Workflow funnel" subtitle="Alert to resolution pipeline" /><ResponsiveContainer width="100%" height={245}><FunnelChart><Tooltip {...TOOLTIP_STYLE} /><Funnel dataKey="count" data={operations.workflowFunnel} isAnimationActive><LabelList position="right" fill="#cbd5e1" stroke="none" dataKey="stage" fontSize={11} /></Funnel></FunnelChart></ResponsiveContainer></div></div>

    <div className="grid lg:grid-cols-2 gap-4 mt-4"><div className="surface-card p-4"><SectionHeader title="Department performance" subtitle="Open work, overdue tasks and average elapsed hours" /><ResponsiveContainer width="100%" height={260}><BarChart data={operations.departmentPerformance} layout="vertical" margin={{ left: 18, right: 18 }}><CartesianGrid strokeDasharray="3 3" stroke="rgba(99,102,241,0.1)" horizontal={false} /><XAxis type="number" tick={{ fill: '#64748b', fontSize: 10 }} /><YAxis type="category" dataKey="department" width={120} tick={{ fill: '#94a3b8', fontSize: 10 }} /><Tooltip {...TOOLTIP_STYLE} /><Bar dataKey="open" fill="#f59e0b" name="Open" radius={[0, 3, 3, 0]} /><Bar dataKey="overdue" fill="#ef4444" name="Overdue" radius={[0, 3, 3, 0]} /></BarChart></ResponsiveContainer><div className="space-y-2 mt-2">{operations.departmentPerformance.map(item => <div key={item.department} className="flex items-center justify-between text-xs"><span className="text-slate-400">{item.department}</span><span className="text-slate-600">{item.averageHours}h avg · {item.resolved} resolved</span></div>)}</div></div><div className="surface-card p-4"><SectionHeader title="Conflict heatmap" subtitle="Village-level concentration from parcel-linked findings" /><div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{operations.heatmap.map(cell => <Link key={cell.village} href={`/map?search=${encodeURIComponent(cell.village)}`} className="rounded-lg border border-slate-800/60 p-3 hover:border-indigo-500/35" style={{ background: `rgba(239,68,68,${Math.max(cell.intensity / 300, 0.03)})` }}><div className="flex items-center gap-1.5"><MapPin size={11} className="text-red-400" /><span className="text-xs text-slate-300 truncate">{cell.village}</span></div><div className="font-heading font-bold text-xl text-white mt-2">{cell.conflicts}</div><div className="text-[10px] text-slate-600">{cell.parcels} parcels · {cell.intensity}% intensity</div></Link>)}</div></div></div>

    <div className="grid lg:grid-cols-3 gap-4 mt-4"><div className="surface-card p-4"><SectionHeader title="Service requests" subtitle="Current request state" />{operations.serviceRequests.map(item => <div key={item.status} className="flex items-center justify-between py-2 border-b border-slate-800/40 last:border-0"><span className="text-xs text-slate-400">{item.status}</span><span className="font-mono text-sm text-white">{item.count}</span></div>)}</div><div className="surface-card p-4"><SectionHeader title="Executive actions" /><div className="space-y-1.5"><Link href="/map" className="nav-item text-xs"><Map size={13} className="text-cyan-400" /> Inspect conflict hotspots</Link><Link href="/workflows" className="nav-item text-xs"><Workflow size={13} className="text-amber-400" /> Escalate overdue workflows</Link><Link href="/alerts" className="nav-item text-xs"><AlertTriangle size={13} className="text-red-400" /> Review critical alerts</Link><Link href="/audit" className="nav-item text-xs"><Activity size={13} className="text-emerald-400" /> Open audit trail</Link></div></div><div className="surface-card p-4"><SectionHeader title="Operational posture" /><div className="flex items-center gap-2 mb-3"><div className="w-2 h-2 rounded-full bg-emerald-400" /><span className="text-sm text-emerald-400">Monitoring active</span></div><div className="text-xs text-slate-500 leading-relaxed">District metrics link to filtered operational screens. GIS remains the primary spatial workspace; this dashboard provides command-level aggregation.</div><div className="mt-4 flex gap-2"><StatusPill value="Synthetic data" tone="warning" /><StatusPill value="Audit enabled" tone="success" /></div></div></div>
  </div></AppShell>;
}
